# import

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 0. 용어 정의

1. axis : 배열의 각 축을 의미

2. rank : 축의 개수

3. shape : (3,4) $\to (3 \times 4 \,\text{by matrix})$ 

# 1. 배열 선언

## (1) 1차원 배열의 선언

`-` 튜플

In [36]:
np.array((1,2,3))

array([1, 2, 3])

`-` 리스트

In [37]:
np.array([1,2,3])

array([1, 2, 3])

`-` range

In [39]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 알아두면 좋은 1차원 배열 선언

In [40]:
np.zeros(3)

array([0., 0., 0.])

In [41]:
np.ones(3)

array([1., 1., 1.])

`-` `np.linspace(2,8,4)` : 2~8까지, 4개의 원소를 생성

In [42]:
np.linspace(2,8,4)

array([2., 4., 6., 8.])

`-` `np.arange(start,end)` : nump버전 range라고 생각하자!

In [45]:
np.arange(5), np.arange(1,6)

(array([0, 1, 2, 3, 4]), array([1, 2, 3, 4, 5]))

### 주의 1. 배열의 자료형

`-` 숫자 $\to$ 문자

In [85]:
a = np.array([1,"A",3.0])
a

array(['1', 'A', '3'], dtype='<U11')

`-` 정수 $\to$ 실수

In [86]:
a = np.array([1,2,3.0])
a

array([1., 2., 3.])

## (2) 2차원 배열의 선언

### list

In [58]:
a1 = [[1,2,3],
     [4,5,6]]

np.array(a1)

array([[1, 2, 3],
       [4, 5, 6]])

### stack

In [60]:
a1 = np.random.randint(0,9,3)
a2 = np.random.randint(0,9,3)

A1 = np.stack([a1,a2],axis=0) 
A1, A1.shape

(array([[0, 4, 2],
        [3, 2, 3]]),
 (2, 3))

In [62]:
A2 = np.stack([a1,a2],axis=1) 
A2, A2.shape

(array([[0, 3],
        [4, 2],
        [2, 3]]),
 (3, 2))

## (3) 3차원 배열의 선언

### list

In [72]:
a = [[[1,2],[3,4]],[[5,6],[7,8]]]
np.array(a), np.array(a).shape

(array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]),
 (2, 2, 2))

### stack + reshape

In [118]:
a1 = np.random.randint(0,9,4)
a2 = np.random.randint(0,9,4)
a3 = np.random.randint(0,9,4)

A1 = np.stack([a1,a2,a3],axis=0).reshape(2,3,2)
A1, A1.shape

(array([[[8, 8],
         [4, 0],
         [6, 8]],
 
        [[8, 4],
         [0, 1],
         [1, 6]]]),
 (2, 3, 2))

In [125]:
A1.dtype

dtype('int32')

***

# 2. 인덱싱 & 슬라이싱

In [154]:
a1 = np.random.randint(0,9,3)
a2 = np.random.randint(0,9,3)
a3 = np.random.randint(0,9,3)
a4 = np.random.randint(0,9,3)

A1 = np.stack([a1,a2,a3,a4],axis=0) 
A1

array([[8, 8, 7],
       [3, 1, 1],
       [3, 5, 7],
       [7, 8, 6]])

## 행 조회

In [155]:
A1[0:2,]

array([[8, 8, 7],
       [3, 1, 1]])

In [156]:
A1[[0,1,2]]

array([[8, 8, 7],
       [3, 1, 1],
       [3, 5, 7]])

In [157]:
A1[[0,1,2], : ]

array([[8, 8, 7],
       [3, 1, 1],
       [3, 5, 7]])

## 열 조회

In [158]:
A1[:,0:2]

array([[8, 8],
       [3, 1],
       [3, 5],
       [7, 8]])

In [159]:
A1[:,[0,1,2]]

array([[8, 8, 7],
       [3, 1, 1],
       [3, 5, 7],
       [7, 8, 6]])

## 행,열 조회

In [160]:
A1[0:2,0:2]

array([[8, 8],
       [3, 1]])

## `stride( start :end : interval)`

In [162]:
A1

array([[8, 8, 7],
       [3, 1, 1],
       [3, 5, 7],
       [7, 8, 6]])

In [161]:
A1[::2, ::2]

array([[8, 7],
       [3, 7]])

## 특정값을 지정하여 접근

In [164]:
A1

array([[8, 8, 7],
       [3, 1, 1],
       [3, 5, 7],
       [7, 8, 6]])

In [170]:
A1[A1==1]

array([1, 1])

In [173]:
A1[A1==7]

array([7, 7, 7])

***

# 3. 넘파이 연산

## 기본 연산

In [6]:
a = np.array([1,2,3])

In [27]:
# | code-fold : true
print(f'''
1. 사칙연산 

a + 1 = {a+1}
a - 2 = {a-2}
a x 2 = {a*2}
a / 2 = {a/2}
a // 2 = {a//2}
a % 2 = {a % 2}

=======================================

2. 거듭제곱, 로그, 지수, 삼각함수

a^2 = {a**2}
sqrt(a) = {np.round(np.sqrt(a),2)}
log(a) = {np.round(np.log(a),2)}
exp(a) = {np.round(np.exp(a),2)}
sin(a),cos(a) = {np.round(np.sin(a),2),np.round(np.cos(a),2)}
''')


1. 사칙연산 

a + 1 = [2 3 4]
a - 2 = [-1  0  1]
a x 2 = [2 4 6]
a / 2 = [0.5 1.  1.5]
a // 2 = [0 1 1]
a % 2 = [1 0 1]


2. 거듭제곱, 로그, 지수, 삼각함수

a^2 = [1 4 9]
sqrt(a) = [1.   1.41 1.73]
log(a) = [0.   0.69 1.1 ]
exp(a) = [ 2.72  7.39 20.09]
sin(a),cos(a) = (array([0.84, 0.91, 0.14]), array([ 0.54, -0.42, -0.99]))



## 기타 연산(전치행렬,역행렬)

In [186]:
a1 = np.random.randint(0,9,3)
a2 = np.random.randint(0,9,3)
a3 = np.random.randint(0,9,3)

A1 = np.stack([a1,a2,a3],axis=0) 
A1

array([[8, 1, 1],
       [2, 1, 4],
       [4, 4, 1]])

`-` 전치행렬

In [187]:
A1.T

array([[8, 2, 4],
       [1, 1, 4],
       [1, 4, 1]])

`-` 역행렬

In [188]:
np.linalg.inv(A1)

array([[ 0.14705882, -0.02941176, -0.02941176],
       [-0.1372549 , -0.03921569,  0.29411765],
       [-0.03921569,  0.2745098 , -0.05882353]])

`-` 행렬연산

$$\bf A^{-1} \times A = {I}$$

$$\bf {I} = \begin{bmatrix} 1 & 0 & \dots & 0 \\
                                                     0 & 1 & \dots & 0 \\
                                                     \dots &\dots &\dots &\dots \\
                                                     0 & 0 & \dots & 1
                                                        \end{bmatrix}$$

In [196]:
np.round(A1 @ np.linalg.inv(A1),2)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0.,  0.,  1.]])

***

# 연습문제

`-` [excercise1](https://gangcheol.github.io/mysite/posts/Lecture/IP/2023-08-04-06.%20numpy.html#exercise-1)

`-` [excercise2](https://gangcheol.github.io/mysite/posts/Lecture/IP/2023-08-04-06.%20numpy.html#exercise)

`-` [excercise3](https://gangcheol.github.io/mysite/posts/Lecture/IP/2023-08-04-07.%20Numpy%20%ED%99%9C%EC%9A%A9.html#%EB%84%98%ED%8C%8C%EC%9D%B4-%ED%99%9C%EC%9A%A9-1) 

`-` [excercise4](https://gangcheol.github.io/mysite/posts/Lecture/IP/2023-08-04-07.%20Numpy%20%ED%99%9C%EC%9A%A9.html#%EB%84%98%ED%8C%8C%EC%9D%B4-%ED%99%9C%EC%9A%A9-2)

***

# ref

`-` [numpy basic](https://gangcheol.github.io/mysite/posts/Lecture/IP/2023-08-04-06.%20numpy.html)

`-` [numpy 활용](https://gangcheol.github.io/mysite/posts/Lecture/IP/2023-08-04-06.%20numpy.html)

`-` [pandas 데이터 핸들링](https://gangcheol.github.io/mysite/posts/Lecture/STDV/2023-05-06-7wk.html#pandas-%EB%8D%B0%EC%9D%B4%ED%84%B0-%ED%95%B8%EB%93%A4%EB%A7%81)

`-` [집계함수 & tidydata](https://gangcheol.github.io/mysite/posts/Lecture/STDV/2023-05-13-8wk.html)

`-` KT aivle school dx track